version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: db-services
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data/raw.sql:/docker-entrypoint-initdb.d/1_raw.sql
      - ./data/preprocess.sql:/docker-entrypoint-initdb.d/2_preprocess.sql
    env_file:
      - .env

volumes:
  db_data: